Repository aditicsalunkhe/Group74-CalorieApp_Server, pull requests merged in 2023-10, with the labels that each got.

#2 Changed application.py and insert_food_data.py
  application.py
  insert_food_data.py
Labels: bug

#4 Changed application.py
  .github/workflows/code_cov.yml
  .github/workflows/unit_test.yml
  application.py
  requirements.txt
Labels: bug

#9 Changed application.py
  .github/workflows/code_cov.yml
  .github/workflows/unit_test.yml
  application.py
Labels: bug

#10 Aditi dev
  application.py
  apps.py
  forms.py
  templates/forgot.html
  templates/login.html
  templates/password_reset.html
  templates/password_reset.txt
  templates/reset_password.html
  tests/application.py
Labels: enhancement

#13 'Enter Calorie' stores information of calories just once.
  application.py
Labels: bug

#15 Aditi dev
  application.py
  templates/dashboard.html
  templates/password_reset.txt
Labels: enhancement

#19 The youtube video tutorial opens in a different tab now.
  templates/dashboard.html
Labels: bug

#20 Calorie Data can be stored for past date
  application.py
  forms.py
  templates/calories.html
Labels: enhancement

#22 delete alert message in homepage and add the message in html
  templates/dashboard.html
Labels: bug

#24 change "welcome email" to "welcome user" on top right of navigation bar
  application.py
  templates/layout.html
Labels: bug

#26 remove links default style in bottom navigation bar
  templates/layout.html
Labels: bug

#28 Changed application.py
  application.py
Labels: bug

#29 Changed application.py
  application.py
Labels: bug

#32 Aditi dev
  application.py
  templates/layout.html
Labels: enhancement

#35 Profile Module
  application.py
  templates/display_profile.html
  templates/user_profile.html
Labels: bug, enhancement

#36 Update code_formatter.yml
  .github/workflows/code_formatter.yml
Labels: bug

#51 refine frontend layout and UI
  static/img/background.jpg
  static/img/discordlogo.png
  static/img/githublogo.png
  static/img/logo.png
  static/img/logo1.png
  static/main.css
  templates/dashboard.html
  templates/layout.html
Labels: enhancement

#52 Implemented the remove functionality
  application.py
  templates/enrolled_workouts.html
Labels: enhancement
